runmode: debug
addr: :3000
name: ROP
url: http://127.0.0.1:3000
max_ping_count: 10
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/rop.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
yunpian:
  apikey: a167cfafc6e2d99668fcaaae0a3ba887
  url_send_sms: https://sms.yunpian.com/v2/sms/single_send.json
jwt_secret: XQiOjE1MjgwMTY5MjIsImlkIjowL
passport:
  appid: rop
  appsecret: Wnhb5XAWv7c1ck8hA8t0sWiXA6iIgPOJ1
hr:
  appid: rop
  appsecret: 8iSHH2yshOhels4MldYSTJxk7kPzunvgm
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: root
local_db:
  name: rop
  addr: 127.0.0.1:3306
  username: root
  password: root
qsc_db:
  name: rop
  addr: 127.0.0.1:3306
  username: root
  password: root